# This file was generated by GoReleaser. DO NOT EDIT.
class Groo < Formula
  desc "Opens the website for the current Git remote"
  homepage "https://github.com/cyberwo1f/groo"
  version "1.0.0"

  on_macos do
    on_arm do
      url "https://github.com/cyberwo1f/groo/archive/refs/tags/v1.0.0.tar.gz"
      sha256 "c0da6e337cd69461514faba83672eaa3fcdd053f47c7e4f6a740631308f3da2a"

      depends_on "go" => :build
    end

    on_intel do
      url "https://github.com/cyberwo1f/groo/releases/download/v1.0.0/groo_macOS_amd64.tar.gz"
      sha256 "7f67204fce789df40ee1188a8111a1e540e8cd3a8cbb9fa0e3e61bb41e048250"
    end
  end

  def install
    if Hardware::CPU.arm?
      system "go", "build", *std_go_args(ldflags: "-X main.Version=#{version}")
    else
      bin.install "groo"
    end
  end

  test do
    system "#{bin}/groo", "--version"
  end
end
