# This file was generated by GoReleaser. DO NOT EDIT.
class Groo < Formula
  desc "groo command is open the web site for current git remote."
  homepage ""
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cyberwo1f/groo/releases/download/v1.0.0/groo_macOS_amd64.tar.gz"
    sha256 "7f67204fce789df40ee1188a8111a1e540e8cd3a8cbb9fa0e3e61bb41e048250"
  elsif OS.linux?
  end

  def install
    bin.install "groo"
  end

  test do
    system "#{bin}/groo -v"
  end
end
